version: '3'

services:
  app-angular:
    build: .
    container_name: app-angular
    ports:
      - 4201:4201
    volumes:
      - ./templates:/etc/nginx/templates      
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    working_dir: /usr/share/nginx/html
  app-web:
    image: nginx:1.25.1-alpine
    container_name: app-web
    restart: always
    working_dir: /usr/share/nginx/html
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-angular
networks:
  backend:
    driver: bridge
volumes:
  cache:
    driver: local
