FROM node:17.9-alpine as build
WORKDIR /app

RUN npm install -g @angular/cli

COPY package.json .
RUN npm config set legacy-peer-deps true
RUN npm install
COPY . .
RUN ng update
RUN ng config -g cli.warnings.versionMismatch false
RUN ng build --configuration production

FROM nginx:1.25.1-alpine
WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html
